// Generated by tools/gen_assets.py - do not edit.
#ifndef ASSETS_H
#define ASSETS_H

#include <stdint.h>

#define FONT_CHARS " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ:!->+=.\',%/"
#define FONT_NCHARS 48
#define FRAME_TILE 240
#define NUM_BOARDS 3
#define BG_FIRST_COLOR 32
#define BG_IMG_WORDS 9600

// sprite tiles and palette banks
#define TILE_NUBBY 0
#define TILE_NUBBY_BLINK 1
#define TILE_NUBBY_BIG 2
#define TILE_NUBBY_BIG_BLINK 6
#define TILE_PEG 10           // 16x16 disc template (4 tiles)
#define TILE_DOT 14
#define TILE_SOCKET 15
#define TILE_ICON(i) (22 + (i) * 4)
#define TILE_PERK(i) (66 + (i) * 4)
#define TILE_LASER_WARN 19
#define TILE_LASER 20
#define TILE_WIND 21
#define TILE_FREE 98        // first unused sprite tile
#define PAL_NUBBY 0
#define PAL_TIER(t) (1 + (t))                   // peg colour by value tier
#define NUM_TIERS 9
#define PAL_FLASH 10
#define PAL_ICON 11
#define PAL_ICON_FLASH 12
#define PAL_ARMOR 13
#define PAL_FX 14

extern const uint16_t font_pal[16];
extern const uint16_t obj_pal[240];
extern const uint16_t title_pal[256];
extern const uint32_t title_tiles[BG_IMG_WORDS];
extern const uint16_t *const board_pal[NUM_BOARDS];
extern const uint32_t *const board_tiles[NUM_BOARDS];
extern const uint32_t obj_tiles[784];
extern const uint32_t font_tiles[1984];

#endif
